name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep -oP 'version := "\K[^\"]+' build.sbt)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update README.md with Latest Version
        run: |
          # Match the line containing "addSbtPlugin" and replace the version part with the latest version
          sed -i "s|\(addSbtPlugin(\"datenwissenschaften\" % \"scalafmt-rules\" % \)\"[^\"]*\"|\1\"$PACKAGE_VERSION\"|" README.md
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Commit and Push README.md Update
        if: steps.check_package_version.outcome != 'failure'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with latest version $PACKAGE_VERSION"
          git push

      - name: Check if package and version already exist on Nexus
        id: check_package_version
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          BASE_URL="https://nexus.datenwissenschaften.com/repository/maven-releases"
          ARTIFACT_PATH="com/datenwissenschaften/scalafmt-rules_2.12/$PACKAGE_VERSION/scalafmt-rules_2.12-$PACKAGE_VERSION.pom"
          RESPONSE=$(curl -u $NEXUS_USER:$NEXUS_PASSWORD -s -o /tmp/nexus_response -w "%{http_code}" "$BASE_URL/$ARTIFACT_PATH")
          
          echo "HTTP Response: $RESPONSE"
          if [[ "$RESPONSE" == "200" && -s /tmp/nexus_response ]]; then
            echo "Version $PACKAGE_VERSION already exists. Exiting."
            exit 1
          else
            echo "Version $PACKAGE_VERSION is not published yet. Continuing..."
          fi

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: sbt

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-ivy2-

      - name: Cache SBT artifacts
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Write Nexus Credentials
        run: |
          echo 'credentials += Credentials("Sonatype Nexus Repository Manager", "nexus.datenwissenschaften.com", "${{ secrets.NEXUS_USER }}", "${{ secrets.NEXUS_PASSWORD }}")' > ~/.sbt/1.0/credentials.sbt
          chmod 600 ~/.sbt/1.0/credentials.sbt

      - name: Publish to Nexus
        if: steps.check_package_version.outcome != 'failure'
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: sbt clean publish
